### ISSUE TITLE
Question about the loss

### ISSUE THREAD

**Issue by E0HYL** [RexYing/gnn-model-explainer#13]
Hi, @RexYing.Thanks for the contribution!
It seems that `feat_mask_ent_loss` is not added to the total loss (in `explainer/explain.py`). Could you make some explainations or is there anything I miss?

**Comment by RexYing** [comment]
Hi! The mask entropy loss can be added to the final loss to encourage the discreteness of the learned mask. It could be added (e.g. in syn5) to make it easier to threshold the masks (since the mask values are more extreme - close to 0 or close to 1). But I didn't add it by default, since many tasks work well without the loss.

**Comment by E0HYL** [comment]
Thanks for the reply, that helps!
